### ISSUE TITLE
Data visualization code issues

### ISSUE THREAD

**Issue by wwwpkol** [zxz267/AvatarJLM#2]
Traceback (most recent call last):
  File "/home/yyh_file/AvatarJLM-main/vis.py", line 94, in <module>
    main(opt)
  File "/home/yyh_file/AvatarJLM-main/vis.py", line 75, in main
    avg_error = evaluate(opt, logger, model, test_loader, save_animation=1)
  File "/home/yyh_file/AvatarJLM-main/test.py", line 41, in evaluate
    vis.save_animation(body_pose=body_parms_gt['body'], savepath=save_video_path_gt, bm = model.bm, fps=60, resolution = (800,800))
  File "/home/yyh_file/AvatarJLM-main/utils/utils_visualize.py", line 174, in save_animation
    mv = MeshViewer(width=imw, height=imh, use_offscreen=True)
  File "/home/yyh_file/AvatarJLM-main/body_visualizer/mesh/mesh_viewer.py", line 59, in __init__
    self.viewer = pyrender.OffscreenRenderer(*self.figsize)
  File "/home/.conda/envs/AvatarJLM/lib/python3.9/site-packages/pyrender/offscreen.py", line 31, in __init__
    self._create()
  File "/home/.conda/envs/AvatarJLM/lib/python3.9/site-packages/pyrender/offscreen.py", line 137, in _create
    egl_device = egl.get_device_by_index(device_id)
  File "/home/.conda/envs/AvatarJLM/lib/python3.9/site-packages/pyrender/platforms/egl.py", line 83, in get_device_by_index
    raise ValueError('Invalid device ID ({})'.format(device_id, len(devices)))
ValueError: Invalid device ID (0)
Thanks for your work, but sadly there seems to be a problem with the pose visualization code. Have you encountered such a problem? Or how to solve it. thank you for your reply！

**Comment by zxz267** [comment]
> Traceback (most recent call last): File "/home/yyh_file/AvatarJLM-main/vis.py", line 94, in main(opt) File "/home/yyh_file/AvatarJLM-main/vis.py", line 75, in main avg_error = evaluate(opt, logger, model, test_loader, save_animation=1) File "/home/yyh_file/AvatarJLM-main/test.py", line 41, in evaluate vis.save_animation(body_pose=body_parms_gt['body'], savepath=save_video_path_gt, bm = model.bm, fps=60, resolution = (800,800)) File "/home/yyh_file/AvatarJLM-main/utils/utils_visualize.py", line 174, in save_animation mv = MeshViewer(width=imw, height=imh, use_offscreen=True) File "/home/yyh_file/AvatarJLM-main/body_visualizer/mesh/mesh_viewer.py", line 59, in **init** self.viewer = pyrender.OffscreenRenderer(*self.figsize) File "/home/.conda/envs/AvatarJLM/lib/python3.9/site-packages/pyrender/offscreen.py", line 31, in **init** self._create() File "/home/.conda/envs/AvatarJLM/lib/python3.9/site-packages/pyrender/offscreen.py", line 137, in _create egl_device = egl.get_device_by_index(device_id) File "/home/.conda/envs/AvatarJLM/lib/python3.9/site-packages/pyrender/platforms/egl.py", line 83, in get_device_by_index raise ValueError('Invalid device ID ({})'.format(device_id, len(devices))) ValueError: Invalid device ID (0) Thanks for your work, but sadly there seems to be a problem with the pose visualization code. Have you encountered such a problem? Or how to solve it. thank you for your reply！

Apologies for the delay in responding. You can attempt to address this issue by the following link: [GitHub Issue #79](https://github.com/HongwenZhang/PyMAF/issues/79).

**Comment by wwwpkol** [comment]
> > 回溯（最近一次调用最后一次）： 文件“/home/yyh_file/AvatarJLM-main/vis.py”，第 94 行，在 main（opt） 中 文件 “/home/yyh_file/AvatarJLM-main/vis.py”，第 75 行，在主avg_error中 = evaluate（opt， logger， model， test_loader， save_animation=1） 文件 “/home/yyh_file/AvatarJLM-main/test.py”，第 41 行，在 evaluate vis.save_animation（body_pose=body_parms_gt['body']， savepath=save_video_path_gt， bm = model.bm，fps=60，分辨率 = （800,800）） 文件“/home/yyh_file/AvatarJLM-main/utils/utils_visualize.py”，第 174 行，save_animation mv = MeshViewer（width=imw， height=imh， use_offscreen=True） 文件“/home/yyh_file/AvatarJLM-main/body_visualizer/mesh/mesh_viewer.py”，第 59 行，**init** self.viewer = pyrender。OffscreenRenderer（*self.figsize） 文件“/home/.conda/envs/AvatarJLM/lib/python3.9/site-packages/pyrender/offscreen.py”，第 31 行，**init** self._create（） 文件“/home/.conda/envs/AvatarJLM/lib/python3.9/site-packages/pyrender/offscreen.py”，第 137 行，_create egl_device = egl.get_device_by_index（device_id） 文件 “/home/.conda/envs/AvatarJLM/lib/python3.9/site-packages/pyrender/platforms/egl.py”，第 83 行，在 get_device_by_index raise ValueError（'无效的设备 ID （{}）'.format（device_id， len（devices））） ValueError：设备 ID 无效 （0） 感谢您的工作，但遗憾的是姿势可视化代码似乎存在问题。你遇到过这样的问题吗？或者如何解决它。感谢您的回复！
> 
> 对于延迟回复，我们深表歉意。您可以尝试通过以下链接解决此问题：[GitHub 问题 #79](https://github.com/HongwenZhang/PyMAF/issues/79)。

Thanks for your reply, I have resolved this issue. But a new problem arose for me. I used OpenVR to obtain the rotation and position of the HTC Vive. After preprocessing the data, the posture obtained through the network was completely incorrect. Do you have any reference for preprocessing data in VR?
<img width="536" alt="image" src="https://github.com/zxz267/AvatarJLM/assets/50726523/8a3008dc-6331-464c-ae2c-3a1c8a0b80f9">

**Comment by zxz267** [comment]
> > > 回溯（最近一次调用最后一次）： 文件“/home/yyh_file/AvatarJLM-main/vis.py”，第 94 行，在 main（opt） 中 文件 “/home/yyh_file/AvatarJLM-main/vis.py”，第 75 行，在主avg_error中 = evaluate（opt， logger， model， test_loader， save_animation=1） 文件 “/home/yyh_file/AvatarJLM-main/test.py”，第 41 行，在 evaluate vis.save_animation（body_pose=body_parms_gt['body']， savepath=save_video_path_gt， bm = model.bm，fps=60，分辨率 = （800,800）） 文件“/home/yyh_file/AvatarJLM-main/utils/utils_visualize.py”，第 174 行，save_animation mv = MeshViewer（width=imw， height=imh， use_offscreen=True） 文件“/home/yyh_file/AvatarJLM-main/body_visualizer/mesh/mesh_viewer.py”，第 59 行，**init** self.viewer = pyrender。OffscreenRenderer（*self.figsize） 文件“/home/.conda/envs/AvatarJLM/lib/python3.9/site-packages/pyrender/offscreen.py”，第 31 行，**init** self._create（） 文件“/home/.conda/envs/AvatarJLM/lib/python3.9/site-packages/pyrender/offscreen.py”，第 137 行，_create egl_device = egl.get_device_by_index（device_id） 文件 “/home/.conda/envs/AvatarJLM/lib/python3.9/site-packages/pyrender/platforms/egl.py”，第 83 行，在 get_device_by_index raise ValueError（'无效的设备 ID （{}）'.format（device_id， len（devices））） ValueError：设备 ID 无效 （0） 感谢您的工作，但遗憾的是姿势可视化代码似乎存在问题。你遇到过这样的问题吗？或者如何解决它。感谢您的回复！
> > 
> > 
> > 对于延迟回复，我们深表歉意。您可以尝试通过以下链接解决此问题：[GitHub 问题 #79](https://github.com/HongwenZhang/PyMAF/issues/79)。
> 
> Thanks for your reply, I have resolved this issue. But a new problem arose for me. I used OpenVR to obtain the rotation and position of the HTC Vive. After preprocessing the data, the posture obtained through the network was completely incorrect. Do you have any reference for preprocessing data in VR? <img alt="image" width="536" src="https://private-user-images.githubusercontent.com/50726523/293871363-8a3008dc-6331-464c-ae2c-3a1c8a0b80f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyNzM0NDcsIm5iZiI6MTcwNDI3MzE0NywicGF0aCI6Ii81MDcyNjUyMy8yOTM4NzEzNjMtOGEzMDA4ZGMtNjMzMS00NjRjLWFlMmMtM2ExYzhhMGI4MGY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAzVDA5MTIyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkZDVjOWIyN2ZlM2Y4ZTZmZjIyNTM4YjUzMDQ4ZjYxY2E0NTgzNzFjNDU0OTNlNGNiMzdjMTcwMDNjYzdkMzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3gl9nGNLHKUI5i7ZiC1nI9HKy6PPRIV8HLgFvLG53Es">

I do not have any experience using OpenVR to obtain the tracking signals of HTC Vive. The results may indicate the coordinate system of the training data is different from your preprocessed data.

**Comment by wwwpkol** [comment]
> > > > 回溯（最近一次调用最后一次）： 文件“/home/yyh_file/AvatarJLM-main/vis.py”，第 94 行，在 main（opt） 中 文件 “/home/yyh_file/AvatarJLM-main/vis.py”，第 75 行，在主avg_error中 = evaluate（opt， logger， model， test_loader， save_animation=1） 文件 “/home/yyh_file/AvatarJLM-main/test.py”，第 41 行，在 evaluate vis.save_animation（body_pose=body_parms_gt['body']， savepath=save_video_path_gt， bm = model.bm，fps=60，分辨率 = （800,800）） 文件“/home/yyh_file/AvatarJLM-main/utils/utils_visualize.py”，第 174 行，save_animation mv = MeshViewer（width=imw， height=imh， use_offscreen=True） 文件“/home/yyh_file/AvatarJLM-main/body_visualizer/mesh/mesh_viewer.py”，第 59 行，**init** self.viewer = pyrender。OffscreenRenderer（*self.figsize） 文件“/home/.conda/envs/AvatarJLM/lib/python3.9/site-packages/pyrender/offscreen.py”，第 31 行，**init** self._create（） 文件“/home/.conda/envs/AvatarJLM/lib/python3.9/site-packages/pyrender/offscreen.py”，第 137 行，_create egl_device = egl.get_device_by_index（device_id） 文件 “/home/.conda/envs/AvatarJLM/lib/python3.9/site-packages/pyrender/platforms/egl.py”，第 83 行，在 get_device_by_index raise ValueError（'无效的设备 ID （{}）'.format（device_id， len（devices））） ValueError：设备 ID 无效 （0） 感谢您的工作，但遗憾的是姿势可视化代码似乎存在问题。你遇到过这样的问题吗？或者如何解决它。感谢您的回复！
> > > 
> > > 
> > > 对于延迟回复，我们深表歉意。您可以尝试通过以下链接解决此问题：[GitHub 问题 #79](https://github.com/HongwenZhang/PyMAF/issues/79)。
> > 
> > 
> > Thanks for your reply, I have resolved this issue. But a new problem arose for me. I used OpenVR to obtain the rotation and position of the HTC Vive. After preprocessing the data, the posture obtained through the network was completely incorrect. Do you have any reference for preprocessing data in VR? <img alt="image" width="536" src="https://private-user-images.githubusercontent.com/50726523/293871363-8a3008dc-6331-464c-ae2c-3a1c8a0b80f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyNzM0NDcsIm5iZiI6MTcwNDI3MzE0NywicGF0aCI6Ii81MDcyNjUyMy8yOTM4NzEzNjMtOGEzMDA4ZGMtNjMzMS00NjRjLWFlMmMtM2ExYzhhMGI4MGY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAzVDA5MTIyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkZDVjOWIyN2ZlM2Y4ZTZmZjIyNTM4YjUzMDQ4ZjYxY2E0NTgzNzFjNDU0OTNlNGNiMzdjMTcwMDNjYzdkMzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3gl9nGNLHKUI5i7ZiC1nI9HKy6PPRIV8HLgFvLG53Es">
> 
> I do not have any experience using OpenVR to obtain the tracking signals of HTC Vive. The results may indicate the coordinate system of the training data is different from your preprocessed data.

Thanks for your reply. What did you use to obtain the data from the headset and controller?

**Comment by zxz267** [comment]
We use the tools provided by our colleagues to record the data from the PICO devices.

**Comment by zxz267** [comment]
> > > > > 回溯（最近一次调用最后一次）： 文件“/home/yyh_file/AvatarJLM-main/vis.py”，第 94 行，在 main（opt） 中 文件 “/home/yyh_file/AvatarJLM-main/vis.py”，第 75 行，在主avg_error中 = evaluate（opt， logger， model， test_loader， save_animation=1） 文件 “/home/yyh_file/AvatarJLM-main/test.py”，第 41 行，在 evaluate vis.save_animation（body_pose=body_parms_gt['body']， savepath=save_video_path_gt， bm = model.bm，fps=60，分辨率 = （800,800）） 文件“/home/yyh_file/AvatarJLM-main/utils/utils_visualize.py”，第 174 行，save_animation mv = MeshViewer（width=imw， height=imh， use_offscreen=True） 文件“/home/yyh_file/AvatarJLM-main/body_visualizer/mesh/mesh_viewer.py”，第 59 行，**init** self.viewer = pyrender。OffscreenRenderer（*self.figsize） 文件“/home/.conda/envs/AvatarJLM/lib/python3.9/site-packages/pyrender/offscreen.py”，第 31 行，**init** self._create（） 文件“/home/.conda/envs/AvatarJLM/lib/python3.9/site-packages/pyrender/offscreen.py”，第 137 行，_create egl_device = egl.get_device_by_index（device_id） 文件 “/home/.conda/envs/AvatarJLM/lib/python3.9/site-packages/pyrender/platforms/egl.py”，第 83 行，在 get_device_by_index raise ValueError（'无效的设备 ID （{}）'.format（device_id， len（devices））） ValueError：设备 ID 无效 （0） 感谢您的工作，但遗憾的是姿势可视化代码似乎存在问题。你遇到过这样的问题吗？或者如何解决它。感谢您的回复！
> > > > 
> > > > 
> > > > 对于延迟回复，我们深表歉意。您可以尝试通过以下链接解决此问题：[GitHub 问题 #79](https://github.com/HongwenZhang/PyMAF/issues/79)。
> > > 
> > > 
> > > Thanks for your reply, I have resolved this issue. But a new problem arose for me. I used OpenVR to obtain the rotation and position of the HTC Vive. After preprocessing the data, the posture obtained through the network was completely incorrect. Do you have any reference for preprocessing data in VR? <img alt="image" width="536" src="https://private-user-images.githubusercontent.com/50726523/293871363-8a3008dc-6331-464c-ae2c-3a1c8a0b80f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyNzM0NDcsIm5iZiI6MTcwNDI3MzE0NywicGF0aCI6Ii81MDcyNjUyMy8yOTM4NzEzNjMtOGEzMDA4ZGMtNjMzMS00NjRjLWFlMmMtM2ExYzhhMGI4MGY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAzVDA5MTIyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkZDVjOWIyN2ZlM2Y4ZTZmZjIyNTM4YjUzMDQ4ZjYxY2E0NTgzNzFjNDU0OTNlNGNiMzdjMTcwMDNjYzdkMzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3gl9nGNLHKUI5i7ZiC1nI9HKy6PPRIV8HLgFvLG53Es">
> > 
> > 
> > I do not have any experience using OpenVR to obtain the tracking signals of HTC Vive. The results may indicate the coordinate system of the training data is different from your preprocessed data.
> 
> Thanks for your reply. What did you use to obtain the data from the headset and controller?


We use the tools provided by our colleagues to record the data from the PICO devices.

**Comment by wwwpkol** [comment]
thank you for your reply

**Comment by wwwpkol** [comment]
<img width="478" alt="image" src="https://github.com/zxz267/AvatarJLM/assets/50726523/70f97ccb-d231-4c0f-88ec-639770360adf">
The current coordinate system is correct, but all postures predicted using the open source network model have huge jitter. I suspect it is a problem with the HCT Vive I am using, and I plan to replace the PICO device. Could you please share the data recording tool and preprocessing code? thanks

**Comment by zxz267** [comment]
> <img alt="image" width="478" src="https://private-user-images.githubusercontent.com/50726523/293930781-70f97ccb-d231-4c0f-88ec-639770360adf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzMzc4NDEsIm5iZiI6MTcwNDMzNzU0MSwicGF0aCI6Ii81MDcyNjUyMy8yOTM5MzA3ODEtNzBmOTdjY2ItZDIzMS00YzBmLTg4ZWMtNjM5NzcwMzYwYWRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA0VDAzMDU0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3MmE3NzM0YTNjZTFhYWQwNGU2YWE0MjYzMDQxOTFhZDcyOWU4ZTg5MWRkZWM4MWEzMGYwYmMwYzQwYmIwZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.a2axLRBsJcSdV_DY7jzTrCCm-EsOZZ_v3EnF3Vf0k1E"> The current coordinate system is correct, but all postures predicted using the open source network model have huge jitter. I suspect it is a problem with the HCT Vive I am using, and I plan to replace the PICO device. Could you please share the data recording tool and preprocessing code? thanks

If you aim to utilize PICO devices for testing purposes, you might consider using the PICO SDK designed for developers, which could potentially help in recording tracking data (although I must admit that I am not well-versed in this particular aspect). Unfortunately, our tools and corresponding code are currently unavailable for release.
Regarding jitter issues, they may stem from discrepancies between the joint alignments in SMPL-H models and the tracking devices. To mitigate this problem to a certain degree, we employ device-specific empirical transformations.
Additionally, we also observe the presence of jitter during testing on the devices, which can be attributed to variations between the training data and the test data to some extent.

**Comment by XuxinBlue** [comment]
> > <img alt="image" width="478" src="https://private-user-images.githubusercontent.com/50726523/293930781-70f97ccb-d231-4c0f-88ec-639770360adf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzMzc4NDEsIm5iZiI6MTcwNDMzNzU0MSwicGF0aCI6Ii81MDcyNjUyMy8yOTM5MzA3ODEtNzBmOTdjY2ItZDIzMS00YzBmLTg4ZWMtNjM5NzcwMzYwYWRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA0VDAzMDU0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3MmE3NzM0YTNjZTFhYWQwNGU2YWE0MjYzMDQxOTFhZDcyOWU4ZTg5MWRkZWM4MWEzMGYwYmMwYzQwYmIwZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.a2axLRBsJcSdV_DY7jzTrCCm-EsOZZ_v3EnF3Vf0k1E"> The current coordinate system is correct, but all postures predicted using the open source network model have huge jitter. I suspect it is a problem with the HCT Vive I am using, and I plan to replace the PICO device. Could you please share the data recording tool and preprocessing code? thanks
> 
> If you aim to utilize PICO devices for testing purposes, you might consider using the PICO SDK designed for developers, which could potentially help in recording tracking data (although I must admit that I am not well-versed in this particular aspect). Unfortunately, our tools and corresponding code are currently unavailable for release. Regarding jitter issues, they may stem from discrepancies between the joint alignments in SMPL-H models and the tracking devices. To mitigate this problem to a certain degree, we employ device-specific empirical transformations. Additionally, we also observe the presence of jitter during testing on the devices, which can be attributed to variations between the training data and the test data to some extent.

Hello, I am very interested in your research in this area, I also have a lot of questions to ask you: 1. The position and pose parameters of the headset and controller are obtained by what software or SDK; 2. Your demo is very stable, perhaps after some Data pre-processing, can you please tell me the specific ideas; 3. If it's too much to talk about, can you give us a copy of the pre-processed JSON (or other format) file that holds the parameter data and the corresponding backup of the recorded video? Thank you very much!

**Comment by zxz267** [comment]
> > > <img alt="image" width="478" src="https://private-user-images.githubusercontent.com/50726523/293930781-70f97ccb-d231-4c0f-88ec-639770360adf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzMzc4NDEsIm5iZiI6MTcwNDMzNzU0MSwicGF0aCI6Ii81MDcyNjUyMy8yOTM5MzA3ODEtNzBmOTdjY2ItZDIzMS00YzBmLTg4ZWMtNjM5NzcwMzYwYWRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA0VDAzMDU0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3MmE3NzM0YTNjZTFhYWQwNGU2YWE0MjYzMDQxOTFhZDcyOWU4ZTg5MWRkZWM4MWEzMGYwYmMwYzQwYmIwZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.a2axLRBsJcSdV_DY7jzTrCCm-EsOZZ_v3EnF3Vf0k1E"> The current coordinate system is correct, but all postures predicted using the open source network model have huge jitter. I suspect it is a problem with the HCT Vive I am using, and I plan to replace the PICO device. Could you please share the data recording tool and preprocessing code? thanks
> > 
> > 
> > If you aim to utilize PICO devices for testing purposes, you might consider using the PICO SDK designed for developers, which could potentially help in recording tracking data (although I must admit that I am not well-versed in this particular aspect). Unfortunately, our tools and corresponding code are currently unavailable for release. Regarding jitter issues, they may stem from discrepancies between the joint alignments in SMPL-H models and the tracking devices. To mitigate this problem to a certain degree, we employ device-specific empirical transformations. Additionally, we also observe the presence of jitter during testing on the devices, which can be attributed to variations between the training data and the test data to some extent.
> 
> Hello, I am very interested in your research in this area, I also have a lot of questions to ask you: 1. The position and pose parameters of the headset and controller are obtained by what software or SDK; 2. Your demo is very stable, perhaps after some Data pre-processing, can you please tell me the specific ideas; 3. If it's too much to talk about, can you give us a copy of the pre-processed JSON (or other format) file that holds the parameter data and the corresponding backup of the recorded video? Thank you very much!

1. While I am not well-versed in this specific aspect, it's plausible that there exists a method to extract tracking signals from the official SDK; however, I cannot confirm this with certainty. The tools I utilize for this purpose are developed by our team and may indeed interface with the SDK. Unfortunately, these proprietary tools are not available for release.
2. We apply device-specific empirical rigid transformations to translate the raw sensor signals into data corresponding to the head and hand joints.
3. You can access some of our testing samples through [this link](https://drive.google.com/file/d/100v17S8a6w13t6TEo_L9mBgLLXMPfX0a/view). Please note that these samples do not include accompanying recorded videos. At present, we are unable to provide test samples that feature synchronized video recordings.

**Comment by XuxinBlue** [comment]
你好！这里是刘志伟的邮箱，你的来信已经收到，谢谢！

**Comment by Recialhot** [comment]
> > > 回溯（最近一次调用最后一次）： 文件“/home/yyh_file/AvatarJLM-main/vis.py”，第 94 行，在 main（opt） 中 文件 “/home/yyh_file/AvatarJLM-main/vis.py”，第 75 行，在主avg_error中 = evaluate（opt， logger， model， test_loader， save_animation=1） 文件 “/home/yyh_file/AvatarJLM-main/test.py”，第 41 行，在 evaluate vis.save_animation（body_pose=body_parms_gt['body']， savepath=save_video_path_gt， bm = model.bm，fps=60，分辨率 = （800,800）） 文件“/home/yyh_file/AvatarJLM-main/utils/utils_visualize.py”，第 174 行，save_animation mv = MeshViewer（width=imw， height=imh， use_offscreen=True） 文件“/home/yyh_file/AvatarJLM-main/body_visualizer/mesh/mesh_viewer.py”，第 59 行，**init** self.viewer = pyrender。OffscreenRenderer（*self.figsize） 文件“/home/.conda/envs/AvatarJLM/lib/python3.9/site-packages/pyrender/offscreen.py”，第 31 行，**init** self._create（） 文件“/home/.conda/envs/AvatarJLM/lib/python3.9/site-packages/pyrender/offscreen.py”，第 137 行，_create egl_device = egl.get_device_by_index（device_id） 文件 “/home/.conda/envs/AvatarJLM/lib/python3.9/site-packages/pyrender/platforms/egl.py”，第 83 行，在 get_device_by_index raise ValueError（'无效的设备 ID （{}）'.format（device_id， len（devices））） ValueError：设备 ID 无效 （0） 感谢您的工作，但遗憾的是姿势可视化代码似乎存在问题。你遇到过这样的问题吗？或者如何解决它。感谢您的回复！
> > 
> > 
> > 对于延迟回复，我们深表歉意。您可以尝试通过以下链接解决此问题：[GitHub 问题 #79](https://github.com/HongwenZhang/PyMAF/issues/79)。
> 
> Thanks for your reply, I have resolved this issue. But a new problem arose for me. I used OpenVR to obtain the rotation and position of the HTC Vive. After preprocessing the data, the posture obtained through the network was completely incorrect. Do you have any reference for preprocessing data in VR? <img alt="image" width="536" src="https://private-user-images.githubusercontent.com/50726523/293871363-8a3008dc-6331-464c-ae2c-3a1c8a0b80f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0MzkwMzAsIm5iZiI6MTcwNDQzODczMCwicGF0aCI6Ii81MDcyNjUyMy8yOTM4NzEzNjMtOGEzMDA4ZGMtNjMzMS00NjRjLWFlMmMtM2ExYzhhMGI4MGY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDA3MTIxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1ZDkwMWU3YTJmNDJlNjE4MzhiNTYzZThlOWVhZTczNTNiM2JkNzU2Njg2YTYyN2YwZWZiOTZjNDNhNTVkNzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.o6mjRnA9oh7VYT85QvMMdNgdntjbfNs6f2cQavFfbdY">

Hello, I'd like to ask how you managed to convert the data into this kind of animation?unity？how to do it？Thank you
