### ISSUE TITLE
IndexError: Caught IndexError in DataLoader worker process 0.

### ISSUE THREAD

**Issue by Recialhot** [zxz267/AvatarJLM#3]
the problem accur,how to solve it?thanks

**Comment by zxz267** [comment]
> the problem accur,how to solve it?thanks

Could you please provide more details?

**Comment by Recialhot** [comment]
[INFO] Update config {'opt': './options/opt_ajlm.json', 'task': 'AvatarJLM', 'protocol': '1', 'checkpoint': 'AvatarJLM-p1-100k.pth', 'vis': False}.
number of GPUs is: 1
LogHandlers setup!
-------------------------------number of test data is 0
Dataset [AMASS_Dataset - test_dataset] is created.
[Model Info] Use GT tracking signals replacement.
[Model Info] Use position token.
[Model Info] Use rotation token.
[Model Info] Use input token.
[Model Info] Total token number is 45.
Training model [ModelAvatarJLM] is created.
Loading model for G [AvatarJLM-p1-100k.pth] ...
Traceback (most recent call last):
  File "D:\SEU\poseEstimate\AvatarJLM\test.py", line 154, in <module>
    main(opt, args.vis)
  File "D:\SEU\poseEstimate\AvatarJLM\test.py", line 141, in main
    _ = evaluate(opt, logger, model, test_loader, save_animation=save_animation)
  File "D:\SEU\poseEstimate\AvatarJLM\test.py", line 18, in evaluate
    for index, test_data in enumerate(test_loader):
  File "D:\Anaconda3\envs\avatarjlm\lib\site-packages\torch\utils\data\dataloader.py", line 630, in __next__
    data = self._next_data()
  File "D:\Anaconda3\envs\avatarjlm\lib\site-packages\torch\utils\data\dataloader.py", line 1345, in _next_data
    return self._process_data(data)
  File "D:\Anaconda3\envs\avatarjlm\lib\site-packages\torch\utils\data\dataloader.py", line 1371, in _process_data
    data.reraise()
  File "D:\Anaconda3\envs\avatarjlm\lib\site-packages\torch\_utils.py", line 694, in reraise
    raise exception
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "D:\Anaconda3\envs\avatarjlm\lib\site-packages\torch\utils\data\_utils\worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "D:\Anaconda3\envs\avatarjlm\lib\site-packages\torch\utils\data\_utils\fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\Anaconda3\envs\avatarjlm\lib\site-packages\torch\utils\data\_utils\fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\SEU\poseEstimate\AvatarJLM\data\dataset_amass.py", line 48, in __getitem__
    filename = self.filename_list[idx]
IndexError: list index out of range

**Comment by zxz267** [comment]
> [INFO] Update config {'opt': './options/opt_ajlm.json', 'task': 'AvatarJLM', 'protocol': '1', 'checkpoint': 'AvatarJLM-p1-100k.pth', 'vis': False}. number of GPUs is: 1 LogHandlers setup! -------------------------------number of test data is 0 Dataset [AMASS_Dataset - test_dataset] is created. [Model Info] Use GT tracking signals replacement. [Model Info] Use position token. [Model Info] Use rotation token. [Model Info] Use input token. [Model Info] Total token number is 45. Training model [ModelAvatarJLM] is created. Loading model for G [AvatarJLM-p1-100k.pth] ... Traceback (most recent call last): File "D:\SEU\poseEstimate\AvatarJLM\test.py", line 154, in main(opt, args.vis) File "D:\SEU\poseEstimate\AvatarJLM\test.py", line 141, in main _ = evaluate(opt, logger, model, test_loader, save_animation=save_animation) File "D:\SEU\poseEstimate\AvatarJLM\test.py", line 18, in evaluate for index, test_data in enumerate(test_loader): File "D:\Anaconda3\envs\avatarjlm\lib\site-packages\torch\utils\data\dataloader.py", line 630, in **next** data = self._next_data() File "D:\Anaconda3\envs\avatarjlm\lib\site-packages\torch\utils\data\dataloader.py", line 1345, in _next_data return self._process_data(data) File "D:\Anaconda3\envs\avatarjlm\lib\site-packages\torch\utils\data\dataloader.py", line 1371, in _process_data data.reraise() File "D:\Anaconda3\envs\avatarjlm\lib\site-packages\torch_utils.py", line 694, in reraise raise exception IndexError: Caught IndexError in DataLoader worker process 0. Original Traceback (most recent call last): File "D:\Anaconda3\envs\avatarjlm\lib\site-packages\torch\utils\data_utils\worker.py", line 308, in _worker_loop data = fetcher.fetch(index) File "D:\Anaconda3\envs\avatarjlm\lib\site-packages\torch\utils\data_utils\fetch.py", line 51, in fetch data = [self.dataset[idx] for idx in possibly_batched_index] File "D:\Anaconda3\envs\avatarjlm\lib\site-packages\torch\utils\data_utils\fetch.py", line 51, in data = [self.dataset[idx] for idx in possibly_batched_index] File "D:\SEU\poseEstimate\AvatarJLM\data\dataset_amass.py", line 48, in **getitem** filename = self.filename_list[idx] IndexError: list index out of range

Could you please provide your data organization? It seems the data is not in the right position for loading.

**Comment by Recialhot** [comment]
i want to run prepare_data.py, it accurs this probelm, but i has this file, thanks 

Traceback (most recent call last):
  File "D:\SEU\poseEstimate\AvatarJLM\data\prepare_data.py", line 24, in <module>
    bm_male = BodyModel(bm_fname=bm_fname_male, num_betas=num_betas, num_dmpls=num_dmpls, dmpl_fname=dmpl_fname_male).to(device)
  File "D:\SEU\poseEstimate\AvatarJLM\human_body_prior\body_model\body_model.py", line 59, in __init__
    smpl_dict = np.load(bm_fname, encoding='latin1')
  File "D:\Anaconda3\envs\avatarjlm\lib\site-packages\numpy\lib\npyio.py", line 427, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: './support_data/body_models/smplh/male/model.npz'

**Comment by Recialhot** [comment]
hello, i can run test.py now, thanks. But the test results did not show any images. Is there any relevant part in the code? How to use it?

**Comment by zxz267** [comment]
> hello, i can run test.py now, thanks. But the test results did not show any images. Is there any relevant part in the code? How to use it?

You can add "--vis"  to the command when you run "test.py" for visualization (after installing all the requirements for visualization).

**Comment by Recialhot** [comment]
it occur this problem : Cannot use face colors with a smooth mesh

[INFO] Update config {'opt': './options/opt_ajlm.json', 'task': 'AvatarJLM', 'protocol': '1', 'checkpoint': './AvatarJLM-p1-100k.pth', 'vis': True}.
number of GPUs is: 1
LogHandlers setup!
-------------------------------number of test data is 536
Dataset [AMASS_Dataset - test_dataset] is created.
[Model Info] Use GT tracking signals replacement.
[Model Info] Use position token.
[Model Info] Use rotation token.
[Model Info] Use input token.
[Model Info] Total token number is 45.
Training model [ModelAvatarJLM] is created.
Loading model for G [./AvatarJLM-p1-100k.pth] ...
24-01-04 14:33:39.290 : testing the sample 0/536
[INFO] Saving animation of sequence-0...
Traceback (most recent call last):
  File "D:\SEU\poseEstimate\AvatarJLM\test.py", line 154, in <module>
    main(opt, args.vis)
  File "D:\SEU\poseEstimate\AvatarJLM\test.py", line 141, in main
    _ = evaluate(opt, logger, model, test_loader, save_animation=save_animation)
  File "D:\SEU\poseEstimate\AvatarJLM\test.py", line 41, in evaluate
    vis.save_animation(body_pose=body_parms_gt['body'], savepath=save_video_path_gt, bm = model.bm, fps=60, resolution = (800,800))
  File "D:\SEU\poseEstimate\AvatarJLM\utils\utils_visualize.py", line 197, in save_animation
    mv.set_static_meshes([checker_mesh, body_mesh])
  File "D:\SEU\poseEstimate\AvatarJLM\body_visualizer\mesh\mesh_viewer.py", line 97, in set_static_meshes
    def set_static_meshes(self, meshes, poses=[]): self.set_meshes(meshes, group_name='static', poses=poses)
  File "D:\SEU\poseEstimate\AvatarJLM\body_visualizer\mesh\mesh_viewer.py", line 88, in set_meshes
    mesh = pyrender.Mesh.from_trimesh(mesh)
  File "D:\Anaconda3\envs\avatarjlm\lib\site-packages\pyrender\mesh.py", line 209, in from_trimesh
    color_0, texcoord_0, primitive_material = Mesh._get_trimesh_props(m, smooth=smooth, material=material)
  File "D:\Anaconda3\envs\avatarjlm\lib\site-packages\pyrender\mesh.py", line 272, in _get_trimesh_props
    raise ValueError('Cannot use face colors with a smooth mesh')
ValueError: Cannot use face colors with a smooth mesh

**Comment by Recialhot** [comment]
Hello, now after running the test.py, the avi file with serial number 0,10,20 will be generated in the results。How to generate video viewing while testing in real time? Or does the code only provide an avi file with a specified sequence number for later review after the end of the run?

**Comment by zxz267** [comment]
> Hello, now after running the test.py, the avi file with serial number 0,10,20 will be generated in the results。How to generate video viewing while testing in real time? Or does the code only provide an avi file with a specified sequence number for later review after the end of the run?

Currently, the code is designed to generate visualizations only after completing the entire sequence prediction. To enable real-time viewing, you will likely need to implement specific modifications.

**Comment by Recialhot** [comment]
> > Hello, now after running the test.py, the avi file with serial number 0,10,20 will be generated in the results。How to generate video viewing while testing in real time? Or does the code only provide an avi file with a specified sequence number for later review after the end of the run?
> 
> Currently, the code is designed to generate visualizations only after completing the entire sequence prediction. To enable real-time viewing, you will likely need to implement specific modifications.

Now run the test file to get the avi file after the run, how to display the full effect in unity, have you done any related work?thank you

**Comment by zxz267** [comment]
> > > Hello, now after running the test.py, the avi file with serial number 0,10,20 will be generated in the results。How to generate video viewing while testing in real time? Or does the code only provide an avi file with a specified sequence number for later review after the end of the run?
> > 
> > 
> > Currently, the code is designed to generate visualizations only after completing the entire sequence prediction. To enable real-time viewing, you will likely need to implement specific modifications.
> 
> Now run the test file to get the avi file after the run, how to display the full effect in unity, have you done any related work?thank you

I am not personally familiar with this particular matter. You might find it helpful to refer to [this](https://github.com/mkocabas/VIBE?tab=readme-ov-file#fbx-and-gltf-output-new-feature) for guidance.

**Comment by Recialhot** [comment]
> > > > Hello, now after running the test.py, the avi file with serial number 0,10,20 will be generated in the results。How to generate video viewing while testing in real time? Or does the code only provide an avi file with a specified sequence number for later review after the end of the run?
> > > 
> > > 
> > > Currently, the code is designed to generate visualizations only after completing the entire sequence prediction. To enable real-time viewing, you will likely need to implement specific modifications.
> > 
> > 
> > Now run the test file to get the avi file after the run, how to display the full effect in unity, have you done any related work?thank you
> 
> I am not personally familiar with this particular matter. You might find it helpful to refer to [this](https://github.com/mkocabas/VIBE?tab=readme-ov-file#fbx-and-gltf-output-new-feature) for guidance.

Hello, your excellent work is trained through 3 points, I now want to see the training and testing effect of 5 points, i need to add 2 points (two feet), where should i improve your code work? Thank you

**Comment by zxz267** [comment]
> > > > > Hello, now after running the test.py, the avi file with serial number 0,10,20 will be generated in the results。How to generate video viewing while testing in real time? Or does the code only provide an avi file with a specified sequence number for later review after the end of the run?
> > > > 
> > > > 
> > > > Currently, the code is designed to generate visualizations only after completing the entire sequence prediction. To enable real-time viewing, you will likely need to implement specific modifications.
> > > 
> > > 
> > > Now run the test file to get the avi file after the run, how to display the full effect in unity, have you done any related work?thank you
> > 
> > 
> > I am not personally familiar with this particular matter. You might find it helpful to refer to [this](https://github.com/mkocabas/VIBE?tab=readme-ov-file#fbx-and-gltf-output-new-feature) for guidance.
> 
> Hello, your excellent work is trained through 3 points, I now want to see the training and testing effect of 5 points, i need to add 2 points (two feet), where should i improve your code work? Thank you

Our network takes masked tracking signals as inputs. In our case, we only take 3 points as inputs and mask other joints. If you want to extend our method to 5 points, you can simply modify the masked joints [here](https://github.com/zxz267/AvatarJLM/blob/9d27b35d612fbb37ef8a18ad052505c84077099a/models/network.py#L169C10-L169C10).

**Comment by Recialhot** [comment]
> > > > > > Hello, now after running the test.py, the avi file with serial number 0,10,20 will be generated in the results。How to generate video viewing while testing in real time? Or does the code only provide an avi file with a specified sequence number for later review after the end of the run?
> > > > > 
> > > > > 
> > > > > Currently, the code is designed to generate visualizations only after completing the entire sequence prediction. To enable real-time viewing, you will likely need to implement specific modifications.
> > > > 
> > > > 
> > > > Now run the test file to get the avi file after the run, how to display the full effect in unity, have you done any related work?thank you
> > > 
> > > 
> > > I am not personally familiar with this particular matter. You might find it helpful to refer to [this](https://github.com/mkocabas/VIBE?tab=readme-ov-file#fbx-and-gltf-output-new-feature) for guidance.
> > 
> > 
> > Hello, your excellent work is trained through 3 points, I now want to see the training and testing effect of 5 points, i need to add 2 points (two feet), where should i improve your code work? Thank you
> 
> Our network takes masked tracking signals as inputs. In our case, we only take 3 points as inputs and mask other joints. If you want to extend our method to 5 points, you can simply modify the masked joints [here](https://github.com/zxz267/AvatarJLM/blob/9d27b35d612fbb37ef8a18ad052505c84077099a/models/network.py#L169C10-L169C10).
def input_processing(self, input_tensor):
        # --------- get input relative information --------- 
        processed_info = {}
        processed_info['global_gt_head_hand_rotation'] = input_tensor[:, :, [15, 20, 21], 0:6].clone()
        processed_info['global_gt_head_hand_position'] = input_tensor[:, :, [15, 20, 21], 12:15].clone()
        processed_info['global_gt_head_position'] = processed_info['global_gt_head_hand_position'][:, :, 0].clone()
        processed_info['relative_gt_head_hand_position'] = processed_info['global_gt_head_hand_position'] - processed_info['global_gt_head_position'][:, :, None]
        # --------- set masked input ------------
        selected_joint_index = list(range(0, 14+1)) + list(range(16, 19+1))
        input_tensor[:, :, selected_joint_index] = torch.ones_like(input_tensor[:, :, selected_joint_index]).cuda() * 0.01
        return input_tensor, processed_info

If I want to change 3 points to 5 points, do all three lines need to be modified?

 processed_info['global_gt_head_hand_rotation'] = input_tensor[:, :, [15, 20, 21], 0:6].clone()
 processed_info['global_gt_head_hand_position'] = input_tensor[:, :, [15, 20, 21], 12:15].clone()
selected_joint_index = list(range(0, 14+1)) + list(range(16, 19+1))

How were the 14, 16, and 19 identified?

**Comment by Recialhot** [comment]
> > > > > > Hello, now after running the test.py, the avi file with serial number 0,10,20 will be generated in the results。How to generate video viewing while testing in real time? Or does the code only provide an avi file with a specified sequence number for later review after the end of the run?
> > > > > 
> > > > > 
> > > > > Currently, the code is designed to generate visualizations only after completing the entire sequence prediction. To enable real-time viewing, you will likely need to implement specific modifications.
> > > > 
> > > > 
> > > > Now run the test file to get the avi file after the run, how to display the full effect in unity, have you done any related work?thank you
> > > 
> > > 
> > > I am not personally familiar with this particular matter. You might find it helpful to refer to [this](https://github.com/mkocabas/VIBE?tab=readme-ov-file#fbx-and-gltf-output-new-feature) for guidance.
> > 
> > 
> > Hello, your excellent work is trained through 3 points, I now want to see the training and testing effect of 5 points, i need to add 2 points (two feet), where should i improve your code work? Thank you
> 
> Our network takes masked tracking signals as inputs. In our case, we only take 3 points as inputs and mask other joints. If you want to extend our method to 5 points, you can simply modify the masked joints [here](https://github.com/zxz267/AvatarJLM/blob/9d27b35d612fbb37ef8a18ad052505c84077099a/models/network.py#L169C10-L169C10).

Hello, based on your suggestion, I have only made changes to these few areas. Is it enough to modify network.py?Do i still need to modify test.py or trans.py？And does mask_num = 2 in def random_mask need to be changed? I think it seems to be blocking other joints, not the selected ones. Thanks!

    def input_processing(self, input_tensor):
        # --------- get input relative information --------- 
        processed_info = {}
        processed_info['global_gt_head_hand_foot_rotation'] = input_tensor[:, :, [15, 20, 21, 10, 11], 0:6].clone()
        processed_info['global_gt_head_hand_foot_position'] = input_tensor[:, :, [15, 20, 21, 10, 11], 12:15].clone()
        processed_info['global_gt_head_position'] = processed_info['global_gt_head_hand_foot_position'][:, :, 0].clone()
        processed_info['relative_gt_head_hand_foot_position'] = processed_info['global_gt_head_hand_foot_position'] - processed_info['global_gt_head_position'][:, :, None]
        # --------- set masked input ------------
        selected_joint_index = list(range(0, 9+1)) + list(range(12, 14+1))+list(range(16, 19+1))
        input_tensor[:, :, selected_joint_index] = torch.ones_like(input_tensor[:, :, selected_joint_index]).cuda() * 0.01
        return input_tensor, processed_info


    def random_mask(self, joint_embedding):
        batch, seq_len = joint_embedding.shape[0], joint_embedding.shape[1]
        for b_idx in range(batch):
            for s_idx in range(seq_len):
                selected_joint_index = list(range(0, 9+1)) + list(range(12, 14+1))+list(range(16, 19+1))
                if self.use_rotation_token:
                    selected_joint_index += list(range(0+22, 9+1+22)) + list(range(12+22, 14+1+22)) + list(range(16+22, 19+1+22))
                mask_num = 2
                random.shuffle(selected_joint_index)
                mask_index = selected_joint_index[:mask_num]
                joint_embedding[b_idx, s_idx, mask_index] = torch.ones_like(joint_embedding[b_idx, s_idx, mask_index]).cuda() * 0.01
        return joint_embedding

    def stage_1(self, input_tensor):
        -----------------------------------
        # gt replace
        if self.gt_head_hand_replace:
            relative_pose_init[:, :, [15, 20, 21, 10, 11]] = processed_info['relative_gt_head_hand_foot_position']
            rotation_init[:, :, [15, 20, 21, 10, 11]] = processed_info['global_gt_head_hand_foot_rotation']

**Comment by Recialhot** [comment]
> > > > > > Hello, now after running the test.py, the avi file with serial number 0,10,20 will be generated in the results。How to generate video viewing while testing in real time? Or does the code only provide an avi file with a specified sequence number for later review after the end of the run?
> > > > > 
> > > > > 
> > > > > Currently, the code is designed to generate visualizations only after completing the entire sequence prediction. To enable real-time viewing, you will likely need to implement specific modifications.
> > > > 
> > > > 
> > > > Now run the test file to get the avi file after the run, how to display the full effect in unity, have you done any related work?thank you
> > > 
> > > 
> > > I am not personally familiar with this particular matter. You might find it helpful to refer to [this](https://github.com/mkocabas/VIBE?tab=readme-ov-file#fbx-and-gltf-output-new-feature) for guidance.
> > 
> > 
> > Hello, your excellent work is trained through 3 points, I now want to see the training and testing effect of 5 points, i need to add 2 points (two feet), where should i improve your code work? Thank you
> 
> Our network takes masked tracking signals as inputs. In our case, we only take 3 points as inputs and mask other joints. If you want to extend our method to 5 points, you can simply modify the masked joints [here](https://github.com/zxz267/AvatarJLM/blob/9d27b35d612fbb37ef8a18ad052505c84077099a/models/network.py#L169C10-L169C10).

I noticed that the pkl file processed by amass has a right-hand coordinate system (x, y, z), but isn't smpl a left-hand coordinate system (x, z, y)? thanks

**Comment by zxz267** [comment]
> > > > > > > Hello, now after running the test.py, the avi file with serial number 0,10,20 will be generated in the results。How to generate video viewing while testing in real time? Or does the code only provide an avi file with a specified sequence number for later review after the end of the run?
> > > > > > 
> > > > > > 
> > > > > > Currently, the code is designed to generate visualizations only after completing the entire sequence prediction. To enable real-time viewing, you will likely need to implement specific modifications.
> > > > > 
> > > > > 
> > > > > Now run the test file to get the avi file after the run, how to display the full effect in unity, have you done any related work?thank you
> > > > 
> > > > 
> > > > I am not personally familiar with this particular matter. You might find it helpful to refer to [this](https://github.com/mkocabas/VIBE?tab=readme-ov-file#fbx-and-gltf-output-new-feature) for guidance.
> > > 
> > > 
> > > Hello, your excellent work is trained through 3 points, I now want to see the training and testing effect of 5 points, i need to add 2 points (two feet), where should i improve your code work? Thank you
> > 
> > 
> > Our network takes masked tracking signals as inputs. In our case, we only take 3 points as inputs and mask other joints. If you want to extend our method to 5 points, you can simply modify the masked joints [here](https://github.com/zxz267/AvatarJLM/blob/9d27b35d612fbb37ef8a18ad052505c84077099a/models/network.py#L169C10-L169C10).
> 
> I noticed that the pkl file processed by amass has a right-hand coordinate system (x, y, z), but isn't smpl a left-hand coordinate system (x, z, y)? thanks

You are correct. AMASS data is indeed processed by converting the root pose to the (x, y, z) coordinate system, which differs from the SMPL model.

**Comment by zxz267** [comment]
> > > > > > > Hello, now after running the test.py, the avi file with serial number 0,10,20 will be generated in the results。How to generate video viewing while testing in real time? Or does the code only provide an avi file with a specified sequence number for later review after the end of the run?
> > > > > > 
> > > > > > 
> > > > > > Currently, the code is designed to generate visualizations only after completing the entire sequence prediction. To enable real-time viewing, you will likely need to implement specific modifications.
> > > > > 
> > > > > 
> > > > > Now run the test file to get the avi file after the run, how to display the full effect in unity, have you done any related work?thank you
> > > > 
> > > > 
> > > > I am not personally familiar with this particular matter. You might find it helpful to refer to [this](https://github.com/mkocabas/VIBE?tab=readme-ov-file#fbx-and-gltf-output-new-feature) for guidance.
> > > 
> > > 
> > > Hello, your excellent work is trained through 3 points, I now want to see the training and testing effect of 5 points, i need to add 2 points (two feet), where should i improve your code work? Thank you
> > 
> > 
> > Our network takes masked tracking signals as inputs. In our case, we only take 3 points as inputs and mask other joints. If you want to extend our method to 5 points, you can simply modify the masked joints [here](https://github.com/zxz267/AvatarJLM/blob/9d27b35d612fbb37ef8a18ad052505c84077099a/models/network.py#L169C10-L169C10).
> 
> I noticed that the pkl file processed by amass has a right-hand coordinate system (x, y, z), but isn't smpl a left-hand coordinate system (x, z, y)? thanks

You are correct. The AMASS data is indeed processed by converting it to the (x, y, z) coordinate system, which results in a different coordinate system from the SMPL model.

**Comment by Recialhot** [comment]
> > > > > > > > Hello, now after running the test.py, the avi file with serial number 0,10,20 will be generated in the results。How to generate video viewing while testing in real time? Or does the code only provide an avi file with a specified sequence number for later review after the end of the run?
> > > > > > > 
> > > > > > > 
> > > > > > > Currently, the code is designed to generate visualizations only after completing the entire sequence prediction. To enable real-time viewing, you will likely need to implement specific modifications.
> > > > > > 
> > > > > > 
> > > > > > Now run the test file to get the avi file after the run, how to display the full effect in unity, have you done any related work?thank you
> > > > > 
> > > > > 
> > > > > I am not personally familiar with this particular matter. You might find it helpful to refer to [this](https://github.com/mkocabas/VIBE?tab=readme-ov-file#fbx-and-gltf-output-new-feature) for guidance.
> > > > 
> > > > 
> > > > Hello, your excellent work is trained through 3 points, I now want to see the training and testing effect of 5 points, i need to add 2 points (two feet), where should i improve your code work? Thank you
> > > 
> > > 
> > > Our network takes masked tracking signals as inputs. In our case, we only take 3 points as inputs and mask other joints. If you want to extend our method to 5 points, you can simply modify the masked joints [here](https://github.com/zxz267/AvatarJLM/blob/9d27b35d612fbb37ef8a18ad052505c84077099a/models/network.py#L169C10-L169C10).
> > 
> > 
> > I noticed that the pkl file processed by amass has a right-hand coordinate system (x, y, z), but isn't smpl a left-hand coordinate system (x, z, y)? thanks
> 
> You are correct. The AMASS data is indeed processed by converting it to the (x, y, z) coordinate system, which results in a different coordinate system from the SMPL model.

Thanks your reply. That means when i use save_animation(body_pose ,...) function to vis, the body_pose is right-hand coordinate system (x, y, z)? that's right?

**Comment by Recialhot** [comment]
> > > > > > > > Hello, now after running the test.py, the avi file with serial number 0,10,20 will be generated in the results。How to generate video viewing while testing in real time? Or does the code only provide an avi file with a specified sequence number for later review after the end of the run?
> > > > > > > 
> > > > > > > 
> > > > > > > Currently, the code is designed to generate visualizations only after completing the entire sequence prediction. To enable real-time viewing, you will likely need to implement specific modifications.
> > > > > > 
> > > > > > 
> > > > > > Now run the test file to get the avi file after the run, how to display the full effect in unity, have you done any related work?thank you
> > > > > 
> > > > > 
> > > > > I am not personally familiar with this particular matter. You might find it helpful to refer to [this](https://github.com/mkocabas/VIBE?tab=readme-ov-file#fbx-and-gltf-output-new-feature) for guidance.
> > > > 
> > > > 
> > > > Hello, your excellent work is trained through 3 points, I now want to see the training and testing effect of 5 points, i need to add 2 points (two feet), where should i improve your code work? Thank you
> > > 
> > > 
> > > Our network takes masked tracking signals as inputs. In our case, we only take 3 points as inputs and mask other joints. If you want to extend our method to 5 points, you can simply modify the masked joints [here](https://github.com/zxz267/AvatarJLM/blob/9d27b35d612fbb37ef8a18ad052505c84077099a/models/network.py#L169C10-L169C10).
> > 
> > 
> > I noticed that the pkl file processed by amass has a right-hand coordinate system (x, y, z), but isn't smpl a left-hand coordinate system (x, z, y)? thanks
> 
> You are correct. The AMASS data is indeed processed by converting it to the (x, y, z) coordinate system, which results in a different coordinate system from the SMPL model.

When I obtained the data of the Pico controller based on OpenVR, what is the specific position relative to the controller? Is it similar to a human palm or wrist? Thanks

left_controller_pose = get_device_pose(poses, openvr.TrackedControllerRole_LeftHand)

def get_device_pose(poses, device_index):
  pose = poses[device_index]
  return pose.mDeviceToAbsoluteTracking

**Comment by Recialhot** [comment]
> > ndeed processed by converting it to the (x, y, z) coordinate system, which results in a different coordinate system from the SMPL model.
> 
> When I obtained the data of the Pico controller based on OpenVR, what is the specific position relative to the controller? Is it similar to a human palm or wrist? Thanks
> 
> left_controller_pose = get_device_pose(poses, openvr.TrackedControllerRole_LeftHand)
> 
> def get_device_pose(poses, device_index): pose = poses[device_index] return pose.mDeviceToAbsoluteTracking

when i run your real_captured_data, the visualization is correct. But when i use my data based(x,y,z),it cause this problem, that's why? thanks you. 

x to right, y to forward, z to up:
![body_100](https://github.com/zxz267/AvatarJLM/assets/64907763/43ae5947-d144-47bc-a27b-1943ddb5248c)


z to forward, x to left, y to up:
![body_100](https://github.com/zxz267/AvatarJLM/assets/64907763/ab650d3d-df9f-4981-81a4-84b2fd0b7c95)



i notice that in real_captured_data, z is the height, but i use z as the height, the result will be poor, only  z to forward, x to left, y to up, it is not poor, but it is different from your data representation, and it is incorrect in the visualization

**Comment by Recialhot** [comment]
> > > > > > > > 您好，现在运行 test.py 后，结果中会生成序列号为 0,10,20 的 avi 文件。如何在实时测试时生成视频观看？或者代码是否仅提供具有指定序列号的 avi 文件，以便在运行结束后稍后查看？
> > > > > > > 
> > > > > > > 
> > > > > > > 目前，该代码设计为仅在完成整个序列预测后生成可视化效果。若要启用实时查看，可能需要实施特定的修改。
> > > > > > 
> > > > > > 
> > > > > > 现在运行测试文件获取avi文件后运行，如何在unity中显示完整的效果，你有没有做过相关的工作？谢谢
> > > > > 
> > > > > 
> > > > > 我个人不熟悉这个具体问题。您可能会发现参考[此内容](https://github.com/mkocabas/VIBE?tab=readme-ov-file#fbx-and-gltf-output-new-feature)以获取指导会很有帮助。
> > > > 
> > > > 
> > > > 您好，你们优秀的作品是通过3点训练的，我现在想看看5点的训练和测试效果，我需要加2点（两尺），我应该在哪里改进你的代码工作？谢谢
> > > 
> > > 
> > > 我们的网络将屏蔽跟踪信号作为输入。在我们的例子中，我们只取 3 个点作为输入并屏蔽其他关节。如果要将我们的方法扩展到 5 个点，可以[简单地在此处](https://github.com/zxz267/AvatarJLM/blob/9d27b35d612fbb37ef8a18ad052505c84077099a/models/network.py#L169C10-L169C10)修改掩码关节。
> > 
> > 
> > 我注意到 amass 处理的 pkl 文件有一个右手坐标系（x、y、z），但 smpl 不是左手坐标系（x、z、y）吗？谢谢
> 
> 你是对的。AMASS 数据确实是通过将其转换为 （x， y， z） 坐标系来处理的，这会导致与 SMPL 模型不同的坐标系。
 
Hello, I would like to ask what you mean by (x,y,z) coordinate system? X to forward, y to left, z to up? Thanks. When I capture real data with (x,y,z) coordinates, I can't test it well with the model, so I'd like to ask you about your coordinate system settings

**Comment by Recialhot** [comment]
> > > > > > > > > 您好，现在运行 test.py 后，结果中会生成序列号为 0,10,20 的 avi 文件。如何在实时测试时生成视频观看？或者代码是否仅提供具有指定序列号的 avi 文件，以便在运行结束后稍后查看？
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 目前，该代码设计为仅在完成整个序列预测后生成可视化效果。若要启用实时查看，可能需要实施特定的修改。
> > > > > > > 
> > > > > > > 
> > > > > > > 现在运行测试文件获取avi文件后运行，如何在unity中显示完整的效果，你有没有做过相关的工作？谢谢
> > > > > > 
> > > > > > 
> > > > > > 我个人不熟悉这个具体问题。您可能会发现参考[此内容](https://github.com/mkocabas/VIBE?tab=readme-ov-file#fbx-and-gltf-output-new-feature)以获取指导会很有帮助。
> > > > > 
> > > > > 
> > > > > 您好，你们优秀的作品是通过3点训练的，我现在想看看5点的训练和测试效果，我需要加2点（两尺），我应该在哪里改进你的代码工作？谢谢
> > > > 
> > > > 
> > > > 我们的网络将屏蔽跟踪信号作为输入。在我们的例子中，我们只取 3 个点作为输入并屏蔽其他关节。如果要将我们的方法扩展到 5 个点，可以[简单地在此处](https://github.com/zxz267/AvatarJLM/blob/9d27b35d612fbb37ef8a18ad052505c84077099a/models/network.py#L169C10-L169C10)修改掩码关节。
> > > 
> > > 
> > > 我注意到 amass 处理的 pkl 文件有一个右手坐标系（x、y、z），但 smpl 不是左手坐标系（x、z、y）吗？谢谢
> > 
> > 
> > 你是对的。AMASS 数据确实是通过将其转换为 （x， y， z） 坐标系来处理的，这会导致与 SMPL 模型不同的坐标系。
> 
> Hello, I would like to ask what you mean by (x,y,z) coordinate system? X to forward, y to left, z to up? Thanks. When I capture real data with (x,y,z) coordinates, I can't test it well with the model, so I'd like to ask you about your coordinate system settings

when i use z to up, wherever x and y are facing, it will cause this:
![body_919](https://github.com/zxz267/AvatarJLM/assets/64907763/b7a37dc6-69bf-4e7f-9d77-bfff44baf7d6)

only when i use z to forward, x to left, y to up, it will cause this, but it not stand and Lifting feet is easy to fluctuate.  when i see dataset_amass or your dataset_tracking, the data always z to up, but final result is right. my data z to up is not success.  That's why? Thanks
![body_100](https://github.com/zxz267/AvatarJLM/assets/64907763/2006a05d-e279-4ad0-9e8b-b217d7124dfa)
