### ISSUE TITLE
你好，我在data_amass.py中将除头部和双手外的关节的输入全部置0，为什么会导致结果很差？

### ISSUE THREAD

**Issue by qianbo-x** [zxz267/AvatarJLM#5]
在推理过程中，其余19个关节的信息应当是不会被模型使用到的，在模型文件中也写了会将其他关节的输入置0，请问是什么情况导致在data_amass.py中将其余关节置0导致结果很差呢？

**Comment by zxz267** [comment]
> 在推理过程中，其余19个关节的信息应当是不会被模型使用到的，在模型文件中也写了会将其他关节的输入置0，请问是什么情况导致在data_amass.py中将其余关节置0导致结果很差呢？

这里的“结果很差”，具体是什么表现呢？可视化的结果很差，还是定量的指标很差？有更具体一点的操作和对应的结果吗？
