### ISSUE TITLE
when i use Real-Captured Data to test，it will cause wrong result

### ISSUE THREAD

**Issue by Recialhot** [zxz267/AvatarJLM#6]
when i use your Real-Captured Data to test，it will cause wrong result.that's why? thank you
![body_997](https://github.com/zxz267/AvatarJLM/assets/64907763/91e2fe06-ab39-4a99-af3e-c763e7a48df1)

**Comment by zxz267** [comment]
> when i use your Real-Captured Data to test，it will cause wrong result.that's why? thank you ![body_997](https://private-user-images.githubusercontent.com/64907763/321879475-91e2fe06-ab39-4a99-af3e-c763e7a48df1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5MDQyMzEsIm5iZiI6MTcxMjkwMzkzMSwicGF0aCI6Ii82NDkwNzc2My8zMjE4Nzk0NzUtOTFlMmZlMDYtYWIzOS00YTk5LWFmM2UtYzc2M2U3YTQ4ZGYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEyVDA2Mzg1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyODI5ZWNkNWI3NDhhODQ0ODEwOTUyYTIxMjc1ODk1NDFmYzkyN2ZhODRmZDQ0MTQ3NmZhYjU4OTE2MTkyZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sAA_FhiLRN39jmaukOHZPxwlwzajuR8YCBK_u0o_Dtw)

Could you provide more details on the result? Has the code been modified?

**Comment by Recialhot** [comment]
> > when i use your Real-Captured Data to test，it will cause wrong result.that's why? thank you ![body_997](https://private-user-images.githubusercontent.com/64907763/321879475-91e2fe06-ab39-4a99-af3e-c763e7a48df1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5MDQyMzEsIm5iZiI6MTcxMjkwMzkzMSwicGF0aCI6Ii82NDkwNzc2My8zMjE4Nzk0NzUtOTFlMmZlMDYtYWIzOS00YTk5LWFmM2UtYzc2M2U3YTQ4ZGYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEyVDA2Mzg1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyODI5ZWNkNWI3NDhhODQ0ODEwOTUyYTIxMjc1ODk1NDFmYzkyN2ZhODRmZDQ0MTQ3NmZhYjU4OTE2MTkyZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sAA_FhiLRN39jmaukOHZPxwlwzajuR8YCBK_u0o_Dtw)
> 
> Could you provide more details on the result? Has the code been modified?

gt image is this, example.
![body_987](https://github.com/zxz267/AvatarJLM/assets/64907763/e2078914-c4d3-412f-844a-e2283d4a3063)

but test image is like above this,is wrong action

when i run amass dataset,it will success, but in real-capture-data, it fail. it need more action?

**Comment by Recialhot** [comment]
> > when i use your Real-Captured Data to test，it will cause wrong result.that's why? thank you ![body_997](https://private-user-images.githubusercontent.com/64907763/321879475-91e2fe06-ab39-4a99-af3e-c763e7a48df1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5MDQyMzEsIm5iZiI6MTcxMjkwMzkzMSwicGF0aCI6Ii82NDkwNzc2My8zMjE4Nzk0NzUtOTFlMmZlMDYtYWIzOS00YTk5LWFmM2UtYzc2M2U3YTQ4ZGYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEyVDA2Mzg1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyODI5ZWNkNWI3NDhhODQ0ODEwOTUyYTIxMjc1ODk1NDFmYzkyN2ZhODRmZDQ0MTQ3NmZhYjU4OTE2MTkyZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sAA_FhiLRN39jmaukOHZPxwlwzajuR8YCBK_u0o_Dtw)
> 
> Could you provide more details on the result? Has the code been modified?

is that Problems with coordinate systems？

**Comment by zxz267** [comment]
> > > when i use your Real-Captured Data to test，it will cause wrong result.that's why? thank you ![body_997](https://private-user-images.githubusercontent.com/64907763/321879475-91e2fe06-ab39-4a99-af3e-c763e7a48df1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5MDQyMzEsIm5iZiI6MTcxMjkwMzkzMSwicGF0aCI6Ii82NDkwNzc2My8zMjE4Nzk0NzUtOTFlMmZlMDYtYWIzOS00YTk5LWFmM2UtYzc2M2U3YTQ4ZGYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEyVDA2Mzg1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyODI5ZWNkNWI3NDhhODQ0ODEwOTUyYTIxMjc1ODk1NDFmYzkyN2ZhODRmZDQ0MTQ3NmZhYjU4OTE2MTkyZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sAA_FhiLRN39jmaukOHZPxwlwzajuR8YCBK_u0o_Dtw)
> > 
> > 
> > Could you provide more details on the result? Has the code been modified?
> 
> is that Problems with coordinate systems？

It seems there may be an issue with the coordinate system, but with the limited information provided, I'm unable to assist in diagnosing the problem. Could you clarify if this issue occurs with the original open-source code or with modified code?
